model:
  in_channels: 3
  image_size: 512
  layer_depths: [64, 128, 128, 256, 512]
  path: /Users/cox.j/PycharmProjects/UF-Eye/trained_models/
  model_name: complex_cnn-1fold.pt

data:
  path: /Users/cox.j/PycharmProjects/UF-Eye/data/processed/fundus

training:
  epochs: 1000
  patience: 150
  batch_size: 1
  lr: 0.0001
  val_fraction: 0.2
  seed: 42
  num_workers: 4
  pin_memory: true
